AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Actions OIDC Integration for AWS Authentication'

Parameters:
  GitHubOrg:
    Type: String
    Description: GitHub organization name
  
  RepositoryName:
    Type: String
    Description: GitHub repository name
  
  BranchName:
    Type: String
    Description: GitHub branch name to allow authentication from
    Default: main

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Tags:
        - Key: Project
          Value: !Ref RepositoryName

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt GitHubOIDCProvider.Arn
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:ref:refs/heads/${BranchName}
      ManagedPolicyArns:
        - !Ref GitHubActionsPolicy
      Tags:
        - Key: Project
          Value: !Ref RepositoryName

  GitHubActionsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for GitHub Actions to deploy resources
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'cloudformation:*'
              - 's3:*'
              - 'lambda:*'
              - 'cloudfront:*'
              - 'route53:*'
              - 'acm:*'
              - 'ssm:*'
              - 'events:*'
              - 'logs:*'
              - 'sns:*'
              - 'sqs:*'
              - 'cloudwatch:*'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'iam:CreateRole'
              - 'iam:DeleteRole'
              - 'iam:GetRole'
              - 'iam:GetRolePolicy'
              - 'iam:PassRole'
              - 'iam:UpdateRole'
              - 'iam:AttachRolePolicy'
              - 'iam:DetachRolePolicy'
              - 'iam:PutRolePolicy'
              - 'iam:DeleteRolePolicy'
              - 'iam:CreatePolicy'
              - 'iam:DeletePolicy'
              - 'iam:CreatePolicyVersion'
              - 'iam:DeletePolicyVersion'
              - 'iam:GetPolicy'
              - 'iam:GetPolicyVersion'
              - 'iam:ListPolicyVersions'
              - 'iam:ListAttachedRolePolicies'
              - 'iam:ListRolePolicies'
              - 'iam:TagRole'
              - 'iam:TagPolicy'
              - 'iam:UntagRole'
              - 'iam:UntagPolicy'
            Resource: '*'

Outputs:
  OIDCProviderArn:
    Description: ARN of the GitHub OIDC Provider
    Value: !GetAtt GitHubOIDCProvider.Arn
  
  RoleARN:
    Description: ARN of the IAM Role for GitHub Actions
    Value: !GetAtt GitHubActionsRole.Arn